version: '3.1'
services:
  stats-server:
    build: stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin


  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stat

  #ewm-service:
  #  ports:
  #    - "8080:8080"

  #ewm-db:
  #  image: postgres:14-alpine
